
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_demo_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
#profile: 'default'
#profile: 'my-snowflake-db'
profile: postgres-db

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

#on-run-start: "insert into dbtdemo.dbt_audit_table (action) values('BUILD_STARTED');commit;"
#on-run-end: "insert into dbtdemo.dbt_audit_table (action) values('BUILD_ENDED'); commit;"
on-run-start: "{{ audits('MAIN','START',NULL) }}"
on-run-end: "{{ audits('MAIN','END',NULL) }}"
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  #pre-hook: "insert into dbtdemo.dbt_audit_table (action) values('MODEL_STARTED');commit;"
  #post-hook: "insert into dbtdemo.dbt_audit_table (action) values('MODEL_ENDED'); commit;"
  #pre-hook: "{{ audits('MODEL_STARTED') }}"
  #post-hook: "{{ audits('MODEL_ENDED') }}"
  dbt_demo_project:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
      +schema: dbtdemo
    snowflake_model_data:
      +materialized: table
      +schema: dbtdemo
    postgres_model:
      +materialized: table
      +schema: dbtdemo
      #pre-hook: "{{ audits('POSTGRES_MODEL','STARTED') }}"
      #post-hook: "{{ audits('POSTGRES_MODEL','ENDED') }}"

seeds:
  dbt_demo_project:
    +schema: dbtdemo
  
vars:
  country: "NA"
  dbt_demo_project:
    country: "USA"

