version: 2

sources:
  - name: sales_data
    description: "Snowflake Source Data"
    database: DEMO_DB
    schema: PUBLIC
    tables:
      - name: orders
        description: 'all the orders placed'
      - name: customers
        description: 'all the customers'
      - name: order_items
        description: 'items related to orders'
      - name: products
        description: 'product cataloge'
      - name: categories
        description: 'product catagories'
      - name: departments
        description: 'customer departments'

models:
  - name: cust_count_by_state
    description: "A Aggregated Table"
    tests:
      - is_not_empty
    columns:
      - name: CUSTOMER_STATE
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      #- name: CUST_COUNT

  - name: customer
    tests:
      - is_not_empty

